### ISSUE TITLE
Problem when using PostgreSQL

### ISSUE THREAD

**Issue by jschuhmacher** [rocket-rentals/redmine-gitosis#2]
In "app/models/gitosis_public_key.rb", the lines:
    STATUS_ACTIVE = 1
    STATUS_LOCKED = 0
are problematic when used with PostgreSQL. The following changes fix it:
    STATUS_ACTIVE = TRUE
    STATUS_LOCKED = FALSE
But I'm not sure if this will work for other databases too.

**Comment by trappist** [comment]
I took care of it by adding a integer=boolean operator like so:

CREATE OR REPLACE FUNCTION inttobool(integer, boolean) RETURNS boolean
AS $$
   SELECT CASE WHEN $1=0 and NOT $2 OR ($1<>0 and $2) THEN true ELSE false END  
$$
LANGUAGE sql;

CREATE OR REPLACE FUNCTION inttobool(boolean, integer) RETURNS boolean
AS $$
   SELECT inttobool($2, $1);
$$
LANGUAGE sql;

CREATE OR REPLACE FUNCTION notinttobool(boolean, integer) RETURNS boolean
AS 
$$
  SELECT NOT inttobool($2,$1);
$$
LANGUAGE sql;

CREATE OR REPLACE FUNCTION notinttobool(integer, boolean) RETURNS boolean
AS $$
    SELECT NOT inttobool($1,$2);
$$
LANGUAGE sql;

CREATE OPERATOR = (
PROCEDURE = inttobool,
LEFTARG = boolean,
RIGHTARG = integer,
COMMUTATOR = =,
NEGATOR = <>
);

CREATE OPERATOR <> (
PROCEDURE = notinttobool,
LEFTARG = integer,
RIGHTARG = boolean,
COMMUTATOR = <>,
NEGATOR = =
);

CREATE OPERATOR = (
PROCEDURE = inttobool,
LEFTARG = integer,
RIGHTARG = boolean,
COMMUTATOR = =,
NEGATOR = <>
);

CREATE OPERATOR <> (
PROCEDURE = notinttobool,
LEFTARG = boolean,
RIGHTARG = integer,
COMMUTATOR = <>,
NEGATOR = =
);

**Comment by manern** [comment]
WARNING: The first comment in this thread is not going to fix it - close but not quite (the to_i on line 13 will break it!)

I just ran into and fixed this today - there are four options (ordered from simplest to most invasive):

1) Add apostrophes around active's value in the SQL so it is interpreted as a literal (gitosis_public_key_controller.rb, line 15):
c = ARCondition.new(@status ? ["active='?'", @status] : nil)
2) Instead of 1/0, use TRUE/FALSE which is the true SQL-92 (section 8.12) compliant way. This requires some slight changes to the gitosis_public_keys controller and model, but more than the first poster indicated.
3) Define active as an integer instead in the database table.
4) Add the integer/bool operator to PostgreSQL.

**Comment by jschuhmacher** [comment]
I missed that one, thanks for the warning.

**Comment by thafreak** [comment]
Oops, I apparently re-reported this issue. Is there any time frame for a fix to be released?
